a_m=10
b_m=15
c_m=18
a_f=11
b_f=13
c_f=15
print("A班的男生有{}人，".format(a_m),end="")
print("B班的男生有{}人，".format(b_m),end="")
print("C班的男生有{}人".format(c_m))
print("A班的女生有{}人，".format(a_f),end="")
print("B班的女生有{}人，".format(b_f),end="")
print("C班的女生有{}人".format(c_f))